Implement new Navbar
FiveEat42/yebalja.com pull request #95
Opened 2020-11-16 03:19 UTC by 365kim

## PR
#### Logo
- Change logo image (white colored)
- Adjust the position of logo image and logo text.

#### Nav_Main
- Set two main items as "Bootcamp", "Topstacks"
- Apply more dynamic hover effect
    - reference. hover effect like [here](https://www.kakaopay.com/)

#### Nav_Sub
- Set sub-items for each of main categories
- Appear when hovering a main item.
- There will be no reload when clicking any 'a' tag.

#### Rolling Notice
- Make it as a separate component.

#### Hamburger
- Only its appearance is implemented

#### File directory Update
- 'components/common' has made and moved the relavant files
- 'components/team' has made and moved the relavant files

## More to do
#### Hamburger
- implement the hamburger menu for Responsive navigation bar
- decide how to show all subcategories for a mobile view
    - bootcamp(7+) : home, 42, ssafy, boostcamp, soma, wootecho, likelion
    - topstacks(6+) : language, frontend, backend, deeplearning, dbms, ide/editor

2020-11-16 07:24 UTC, taelee42 approved these changes
코드 잘봤습니다.
더미 데이터 부분 탑스택스랑 기존 navlist랑 같은 구조여서 디비 만들때 어렵지 않을거 같아요!!
컴포넌트별로 폴더가 생겨서 훨씬 깔끔하네요
호버할때 밑줄효과 쩌네요!
![image](https://user-images.githubusercontent.com/55867479/99223513-fc7fc680-2827-11eb-9aaf-7f1579d1e311.png)

마지막으로 여기 화살표가 삐져나온거 같아요!

2020-11-16 07:35 UTC, kirrikirri42 requested changes
### 0. 호버 효과
내비바 수고 많으셨습니다! 
호버효과 너무 이쁘고 좋아요! 미쵸따 👍👍🏻👍🏼👍🏽👍🏾👍🏿 
첨부하신 카카오보다 훠어어어얼씬 이뻐요!
얇으니까 네온느낌 나서 좋군요 제가 형광색 좋아하는거 또 어떻게 아시고 참 🥰

### 1. 텍스트로고 배치
음 개인적으로 예전의 로고줄, 내비줄 요렇게 총 두줄이 시원시원하고 이쁜 것 같습니다만
지금이 확실히 깔끔하긴하네요
또 두줄로 하면 항목이 두개랑 허전할 것 같기도.. 흠 🤔
그치만 또 파란 로고가 이쁘구... 🤯
![image](https://user-images.githubusercontent.com/52592748/99224391-95fba800-2829-11eb-8c73-2b64e571aa1e.png)


### 2. 폰트
내비바에서 호버했을 때 submenu들이 촤라락 gmarket sans로 나오는게 너무너무 이쁘지만!
(촤라락 내려온 애들이 개인적으로 진짜 깔끔하고 완전 맘에 들어요!)
그치만ㅜ 점보트론 글귀 등 다른 텍스트와 이질감이 드는 것 같아서
텍스트로고만 포인트용으로 남겨두고 
나머지는 폰트 통일시키는건 어떨까 조심스레 의견내봅니당!

### 3. 내비바 내부 배치
그리고 부트캠프랑 탑스택의 간격이 좀 널찍이 떨어져있으면 몬가 더 시원시원한 느낌이 날 것 같아요!

### 4. 롤링텍스트 popover
![image](https://user-images.githubusercontent.com/52592748/99222214-6ea2dc00-2825-11eb-9549-1ddabb0f6450.png)
롤링텍스트에서 popover(더보기, 자세히) 버튼이 아래로 내려온 것 같습니다

---

컴포넌트 분리와 컴포넌트 종류별로 디렉토리 분리 너무 좋습니다!
더미데이타까지 만드셨다니 멋져요!
저번에 작은 이견이라도 있으면 승인 하지 말기로 했던 것 같아서 일단 코멘트로 달겠습니닷
수고 많으셨어용👏👏🏻👏🏼👏🏽👏🏾👏🏿

2020-11-17 23:52 UTC, 365kim commented on front/components/temp/NavSub.module.css
> +  font-weight: 600;
이건 클래스를 주었는데 왜인지 적용이 안되더라구요! 계속 시도중이었습니다..!

2020-11-17 23:52 UTC, 365kim commented on front/components/Table.js
> +          <br /> <br />
프리티어가 알아서 저장해줬어용!

2020-11-17 23:53 UTC, 365kim commented
어제 회의 때 수정된 내용이 많아서 정리해서 다시 올리겠습니다!
- (첫째줄) 흰바탕 로고 한줄
- (둘째줄) 어디서배울까 + 나열
- (셋째줄) 무엇을배울까 + 나열

2020-11-18 00:31 UTC, closed without merging