Forest admin/taelee
FiveEat42/yebalja.com pull request #99
Opened 2020-11-18 14:12 UTC by taelee42

- Admin feature: implemented in admin folder. And moved into back folder.
- Add deploy commands: In front and back package.json file, 2 commands are added.
`npm run deploy`: For deploying the server
`npm stop`: For killing the server('run' can be omitted in 'npm start' and 'npm stop')
- Delete outdated files: I deleted package.json and package-lock.json in root folder. 
I think they are not used now, so let me know if they are needed.

2020-11-19 05:27 UTC, taelee42 commented
Admin폴더는 Forest Admin이 직접 만들어준거라 코드는 안보셔도 괜찮습니다~
front/package.json
back/package.json
/package.json이 사라진거
파일은 이렇게 세개만 봐주시면 됩니다~

2020-11-19 05:47 UTC, 365kim approved these changes
아하 `admin/` 전체를 만들어준거군용!
설명 감사합니다! 수고하셨습니다!!! 🙆‍♀️🙆‍♀️🙆‍♀️
백분들 최고!!! 👍💪👍

2020-11-19 05:51 UTC, taelee42 commented on back/admin/yebalja_admin/app.js
> +const express = require('express');
헐 맞습니다!!
admin이 하나의 새로운 서버에요 
package.json도 있답니다. 
까먹고 언급을 못했는데 여기에도 GCP에서 실행할 때 쉽게 하려고
npm run deploy랑 npm stop을 만들어뒀습니다.(start는 forest admin이 만들어줬어요)
![image](https://user-images.githubusercontent.com/55867479/99626897-8cb34b00-2a76-11eb-9647-eaed56533c17.png)

2020-11-19 06:12 UTC, taelee42 commented on back/admin/yebalja_admin/forest/gisus.js
> +});
admin폴더만 제가 만들고 그 안에 yebalja_admin부터는 전부 다 forest admin이 만들어줫어요
(정확히 말하면 lumber라는 라이브러리가 만들어줬어요)

이해를 위해 프로세스를 설명 드리면
1. 프로젝트 이름을 입력(저희의 경우 yebalja_admin)하고 
2. 데이터베이스의 종류(mysql, mssql등등)을 정하고 
3. 데이터베이스의 정보(id, password)등의 정보를 사이트에서 입력하면

![image](https://user-images.githubusercontent.com/55867479/99628115-dac94e00-2a78-11eb-886d-6d78877d3661.png)
아래와 같은 명령어를 치라고 알려줘요
4. lumber 설치: lumber 가 백폴더의 데이터베이스 정보를 읽고 그것을 바탕으로 위에서 정했던 프로젝트명의 폴더에 forest admin 서버파일을 다 생성해주는거 같아요 (즉 yebalja_admin폴더는 lumber라는 라이브러리가 다 만들어줬습니다.)
5. 그리고 폴더안에 들어가서 npm i 로 라이브러리 전부다 설치하고 npm start하면 서버가 돌아갑니다.

2020-11-19 07:20 UTC, taelee42 commented on back/admin/yebalja_admin/app.js
> +}
yebalja_admin안에 .env파일에 여러 설정사항들이 저장되는데요
거기에 CORS를 설정할 수 있는 부분이 있어요
![image](https://user-images.githubusercontent.com/55867479/99633753-c427f480-2a82-11eb-9df2-859565a12df4.png)
아마 여기에 CORS를 열어줄 사이트의 주소를 ','를 구분자로 사용해서 입력하는거 같아요
예를들어
CORS="https://api.yebalja.com","https://www.yebalja.com"
이런식으로요
그러면 위의 코드에서 ,로 split한다음에 allowedOrigins에 추가 저장되는거 같습니다.
forestadmin은 이미 allowedOrigins에 저장되어 있어서 forestadmin사이트에서 접근가능한거 같습니다.

2020-11-19 07:25 UTC, taelee42 commented on back/admin/yebalja_admin/models/categories.js
> +// This model was generated by Lumber. However, you remain in control of your models.
이거도 위에서 언급한 Lumber가 다 만들어주었습니다.
안에 내용을 보니 sequelize의 문법으로 저장되어 있는거 같습니다.
참고로 model은 mysql에서 table을 의미하는 sequelize 용어인거 같습니다.

2020-11-19 07:26 UTC, taelee42 commented on back/package.json
> +    "stop": "pm2 kill"
감사합니다. 
이런 서버용 명령어가 오랜만에 보면 항상 기억이 잘 안나서 항상 package.json에 적어놓는게 좋겠다는 생각이 들었어요

2020-11-19 07:28 UTC, taelee42 commented on front/package.json
> +	"deploy": "NODE_ENV=production pm2 start npx --name 'front-server' -- next start",
헐 습관적으로 tab을 눌러버렸나봐요 
바꿔놓겠습니다~

2020-11-20 03:47 UTC, SeongsangCHO requested changes
db_config.js 5번라인에 ENV오타난 것 같습니다~!

2020-11-20 03:47 UTC, SeongsangCHO commented on back/admin/yebalja_admin/Dockerfile
> +FROM node:10-alpine
폴더 자체가 서버로 돌아간다는 부분에서 약간 이해가 안간채로 넘어갔는데 도커였군요 그럼 이해가 숑 가버렸습니당

2020-11-20 03:47 UTC, SeongsangCHO commented on back/admin/yebalja_admin/models/gisus.js
> +      foreignKey: {
옹 이게 시퀄라이즈에서 외래키 지정하는 방식이군요 완전 편하네요 !

2020-11-20 03:47 UTC, SeongsangCHO commented on back/config/db_config.js
> +  host: process.env.NODE_NEV == "production" ? "localhost" : "34.64.143.77",
오 오타스 ENV?

2020-11-21 07:44 UTC, taelee42 commented on back/admin/yebalja_admin/models/gisus.js
> +      foreignKey: {
오 맞습니다. hasMany, hasOne, belongsTo 이런키워드들로 설정하는거 같습니다.!

2020-11-21 07:44 UTC, taelee42 commented on back/admin/yebalja_admin/Dockerfile
> +FROM node:10-alpine
숑~!

2020-11-21 07:44 UTC, taelee42 commented on back/config/db_config.js
> +  host: process.env.NODE_NEV == "production" ? "localhost" : "34.64.143.77",
헐랭구 감사드립니다!!

2020-11-24 04:59 UTC, SeongsangCHO approved these changes
어푸푸푸~~

2020-11-25 15:32 UTC, merged